(define (problem gsoko1a)
(:domain wieze)
(:objects x y z k1 k2 k3 k4 k5 )
(:init
(palik x)
(palik y)
(palik z)
(mniejszy k1 k2)
(mniejszy k1 k3)
(mniejszy k1 k4)
(mniejszy k1 k5)
(mniejszy k2 k3)
(mniejszy k2 k4)
(mniejszy k2 k5)
(mniejszy k3 k4)
(mniejszy k3 k5)
(mniejszy k4 k5)
(napaliku x k1)
(napaliku x k2)
(napaliku x k3)
(napaliku x k4)
(napaliku x k5)
)
(:goal (and
( napaliku z k1  )
( napaliku z k2  )
( napaliku z k3  )
( napaliku z k4  )
( napaliku z k5  )
))
)