(define (problem p1)
    (:domain blocks)
    (:objects
        a b c d e f
    )
    (:init
        (on-floor a)
        (clear a)
        (on-floor b)
        (clear b)
        (on-floor c)
        (clear c)
        (on-floor d)
        (clear d)
        (on-floor e)
        (clear e)
        (on-floor f)
        (clear f)
        (hand-empty)
    )
    (:goal (and
    (on-floor a)  
    (on-top b a)  
    (on-top c b)  
    (on-top d c)  
    (on-top e d)  
    (on-top f e)  
    (clear f)      
)
)
)